In [87]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
import seaborn as sns
import statsmodels.api as sm

In [88]:
df = pd.read_csv("water_consumption.csv", sep = '\t')
df

     initial  final  price  month  year block  apartment
0       3535   3565  464.1      7  2023     A         11
1       3375   3402  380.1      7  2023     A         12
2       3620   3651  492.1      7  2023     A         21
3       4681   4707  352.1      7  2023     A         22
4       2400   2425  324.1      7  2023     A         31
..       ...    ...    ...    ...   ...   ...        ...
385     2576   2586   71.7      7  2023     G        202
386     2142   2163  212.1      7  2023     G        211
387     2682   2703  212.1      7  2023     G        212
388     1992   2028  632.1      7  2023     G        221
389     1082   1097  380.1      7  2023     G        222

[390 rows x 7 columns]

In [89]:
df['delta'] = df['final'] - df['initial']

In [90]:
le = LabelEncoder()
df['block'] = le.fit_transform(df['block'])
df['apartment'] = le.fit_transform(df['apartment'])

X = df[['final','initial']]
y = df['price']

model = LinearRegression()
model.fit(X, y)

print('R-quadrado:', model.score(X, y))
print('Intercepto:', model.intercept_)
print('Coeficientes:', model.coef_)

X = sm.add_constant(X)
model = sm.OLS(y, X).fit()

print(model.summary())

R-quadrado: 0.7953837528998065
Intercepto: -117.80196347372942
Coeficientes: [ 19.03414068 -19.03554223]
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.795
Model:                            OLS   Adj. R-squared:                  0.794
Method:                 Least Squares   F-statistic:                     752.2
Date:                Mon, 04 Mar 2024   Prob (F-statistic):          4.64e-134
Time:                        11:48:28   Log-Likelihood:                -2354.1
No. Observations:                 390   AIC:                             4714.
Df Residuals:                     387   BIC:                             4726.
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -117.8020     14.848     -7.934      0.000    -146.995     -88.609
final         19.0341      0.556     34.219      0.000      17.940      20.128
initial      -19.0355      0.559    -34.057      0.000     -20.134     -17.937
==============================================================================
Omnibus:                      495.523   Durbin-Watson:                   1.575
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            67639.220
Skew:                           5.854   Prob(JB):                         0.00
Kurtosis:                      66.446   Cond. No.                     1.19e+04
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.19e+04. This might indicate that there are
strong multicollinearity or other numerical problems.